apiVersion: custom.greendeploy.io/v1
kind: VmTemplate
metadata:
  name: my-gdpr-test-vm
  labels:
    data_residency: gdpr # The label our GDPR policy looks for
spec:
  duration_hours: 10
  cpu: "10"
  ram: "8Gi"