apiVersion: custom.greendeploy.io/v1
kind: VmTemplate
metadata:
  name: my-gdpr-test-vm
  labels:
    data_residency: gdpr # The label our GDPR policy looks for
spec:
  duration_hours: 12
  cpu: "6"
  ram: "12Gi"