apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  type: ClusterIP
  selector:
    app: carbon-webhook
  ports:
    - protocol: TCP
      port: 443 # The service listens on the standard HTTPS port
      targetPort: 8443 # and forwards to our container's port